name: Email Action Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: 24f3002443@ds.study.iitm.ac.in
        run: echo "Triggered by push to main"
